// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zCoach.Entities.ThaiNH.Models;

public partial class CoachThaiNh
{
    public int CoachThaiNhid { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public string Address { get; set; }

    public string ImageUrl { get; set; }

    public string Experience { get; set; }

    public string Certification { get; set; }

    public decimal? Salary { get; set; }

    public DateTime? HireDate { get; set; }

    public int? Status { get; set; }

    public DateTime? PublishDate { get; set; }

    public DateTime? UpdateAt { get; set; }

    public int? SpecializationThaiNhid { get; set; }

    public bool IsActive { get; set; }

    public virtual SpecializationThaiNh SpecializationThaiNh { get; set; }
}