// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zCoach.Entities.ThaiNH.Models;

public partial class SpecializationThaiNh
{
    public int SpecializationThaiNhid { get; set; }

    public string SpecializationName { get; set; }

    public string Description { get; set; }

    public int? Status { get; set; }

    public DateTime? PublishDate { get; set; }

    public virtual ICollection<CoachThaiNh> CoachThaiNhs { get; set; } = new List<CoachThaiNh>();
}